package az.petek.explorer.domain

import java.net.URI
import java.time.Instant

/**
 * A campaign YAML generated by code from a site model, waiting for the owner's approval. It passed the campaign
 * validator when it was made. [covered] and [skipped] explain it: which test ideas became which steps, and why the
 * others did not.
 */
data class ScenarioDraft(
    val id: String,
    val explorationId: ExplorationId,
    val modelVersion: Int,
    val target: URI,
    val name: String,
    val yaml: String,
    val covered: List<CoveredIdea>,
    val skipped: List<SkippedIdea>,
    val createdAt: Instant,
)

data class CoveredIdea(
    val idea: TestIdea,
    val stepIds: List<String>,
)

data class SkippedIdea(
    val idea: TestIdea,
    val reason: String,
)
