/*
 * Pətək — multi-agent AI test platform. https://github.com/aslan564/Petek
 * Copyright (c) 2026 Kodcraft. Author: Aslan Aslanov. All rights reserved.
 *
 * Licensed under the Business Source License 1.1 (the "License"); you may not use this file except in
 * compliance with the License. See the LICENSE file in the repository root. Change Date: 2030-09-25;
 * Change License: Apache License, Version 2.0. The Licensed Work is provided "AS IS", without warranty.
 */

package az.petek.explorer.domain

import java.net.URI
import java.time.Instant

/**
 * A campaign YAML generated by code from a site model, waiting for the owner's approval. It passed the campaign
 * validator when it was made. [covered] and [skipped] explain it: which test ideas became which steps, and why the
 * others did not.
 */
data class ScenarioDraft(
    val id: String,
    val explorationId: ExplorationId,
    val modelVersion: Int,
    val target: URI,
    val name: String,
    val yaml: String,
    val covered: List<CoveredIdea>,
    val skipped: List<SkippedIdea>,
    val createdAt: Instant,
)

data class CoveredIdea(
    val idea: TestIdea,
    val stepIds: List<String>,
)

data class SkippedIdea(
    val idea: TestIdea,
    val reason: String,
)
